stages:
  - compose

compose-job:
  stage: compose
  tags:
    - privileged
  script:
    - echo "Preparing Build Enviroment..."

    - sudo dnf install ostree rpm-ostree rclone -y
    - mkdir build-tree
    - mkdir -p ~/.config/rclone && cp $RCLONE_CONFIG ~/.config/rclone/rclone.conf
    - rclone -P sync tau:innatical-tau build-tree
    - gpg --import $GPG_PRIVATE_KEY

    - echo "Building Home..."

    - cd Home
    - sudo rpm-ostree compose tree core.yaml --repo ../build-tree
    - sudo chmod -R 777 ../build-tree
    - ostree summary --repo ../build-tree -u
    - ostree gpg-sign --repo ../build-tree tau/home/1/x86_64 5D155AF6F77C8C9B 
    - cd ..

    - echo "Building Core..."

    - cd Core
    - sudo rpm-ostree compose tree core.yaml --repo ../build-tree
    - sudo chmod -R 777 ../build-tree
    - ostree summary --repo ../build-tree -u
    - ostree gpg-sign --repo ../build-tree tau/core/1/x86_64 5D155AF6F77C8C9B 
    - cd ..

    - echo "Uploading Tree..."

    - rclone -P sync build-tree tau:innatical-tau
