# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: docker pull fedora && docker create fedora && docker exec fedora sudo yum install ostree rpm-ostree
