include:
  - project: 'tauOS/ci'
    file: '/.ostree-build-template.yml'

stages:
  - compose

core-x86_64:
  stage: compose
  tags:
    - privileged
  variables:
    OSTREE_REF: tau/core/1/x86_64
    OS_VARIANT: Core
  extends: .build
  
home-x86_64:
  stage: compose
  tags:
    - privileged
  variables:
    OSTREE_REF: tau/home/1/x86_64
    OS_VARIANT: Home
  extends: .build
