name: Compose OSTree

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  core-x86_64-build:
    uses: tau-OS/github-actions/.github/workflows/build-ostree.yml@main
    with:
      ostreeRef: tau/core/1.1/x86_64
      osVariant: Core
      osName: core-x86_64
  core-x86_64-sign:
    needs: core-x86_64-build
    uses: tau-OS/github-actions/.github/workflows/sign-ostree.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      ostreeRef: tau/core/1.1/x86_64
      osName: core-x86_64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  core-x86_64-upload:
    needs: core-x86_64-sign
    uses: tau-OS/github-actions/.github/workflows/upload-ostree.yml@main
    with:
      osName: core-x86_64
    secrets:
      privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
      teleportSshPrivateKey: ${{ secrets.TELEPORT_SSH_PRIVATE_KEY }}
  home-x86_64-build:
    uses: tau-OS/github-actions/.github/workflows/build-ostree.yml@main
    with:
      ostreeRef: tau/home/1.1/x86_64
      osVariant: Home
      osName: home-x86_64
  home-x86_64-sign:
    needs: home-x86_64-build
    uses: tau-OS/github-actions/.github/workflows/sign-ostree.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      ostreeRef: tau/home/1.1/x86_64
      osName: home-x86_64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  home-x86_64-upload:
    needs: home-x86_64-sign
    uses: tau-OS/github-actions/.github/workflows/upload-ostree.yml@main
    with:
      osName: home-x86_64
    secrets:
      privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
      teleportSshPrivateKey: ${{ secrets.TELEPORT_SSH_PRIVATE_KEY }}
