name: Compose OSTree

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  core-x86_64-build:
    uses: tau-OS/github-actions/.github/workflows/build-ostree.yml@main
    with:
      ostreeRef: tau/core/1.1/x86_64
      osVariant: Core
      osName: core-x86_64
  core-x86_64-sign:
    needs: core-x86_64-build
    uses: tau-OS/github-actions/.github/workflows/sign-ostree.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      ostreeRef: tau/core/1.1/x86_64
      osName: core-x86_64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  core-x86_64-upload:
    needs: core-x86_64-sign
    uses: tau-OS/github-actions/.github/workflows/upload-ostree.yml@main
    with:
      osName: core-x86_64
    secrets:
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}
  home-x86_64-build:
    uses: tau-OS/github-actions/.github/workflows/build-ostree.yml@main
    with:
      ostreeRef: tau/home/1.1/x86_64
      osVariant: Home
      osName: home-x86_64
  home-x86_64-sign:
    needs: home-x86_64-build
    uses: tau-OS/github-actions/.github/workflows/sign-ostree.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      ostreeRef: tau/home/1.1/x86_64
      osName: home-x86_64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  home-x86_64-upload:
    needs: home-x86_64-sign
    uses: tau-OS/github-actions/.github/workflows/upload-ostree.yml@main
    with:
      osName: home-x86_64
    secrets:
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}
  workstation-x86_64-build:
    uses: tau-OS/github-actions/.github/workflows/build-ostree.yml@main
    with:
      ostreeRef: tau/workstation/22/x86_64
      osVariant: Workstation
      osName: workstation-x86_64
      unifiedCore: true
  workstation-x86_64-sign:
    needs: workstation-x86_64-build
    uses: tau-OS/github-actions/.github/workflows/sign-ostree.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      ostreeRef: tau/workstation/22/x86_64
      osName: workstation-x86_64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  workstation-x86_64-upload:
    needs: workstation-x86_64-sign
    uses: tau-OS/github-actions/.github/workflows/upload-ostree.yml@main
    with:
      osName: workstation-x86_64
    secrets:
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}
  server-x86_64-build:
    uses: tau-OS/github-actions/.github/workflows/build-ostree.yml@main
    with:
      ostreeRef: tau/workstation/22/x86_64
      osVariant: Server
      osName: server-x86_64
      unifiedCore: true
  server-x86_64-sign:
    needs: server-x86_64-build
    uses: tau-OS/github-actions/.github/workflows/sign-ostree.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      ostreeRef: tau/server/22/x86_64
      osName: workstation-x86_64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  server-x86_64-upload:
    needs: server-x86_64-sign
    uses: tau-OS/github-actions/.github/workflows/upload-ostree.yml@main
    with:
      osName: server-x86_64
    secrets:
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}nya

  core-aarch64-build:
    uses: tau-OS/github-actions/.github/workflows/build-ostree.yml@main
    with:
      ostreeRef: tau/core/1.1/aarch64
      osVariant: Core
      osName: core-aarch64
      runs-on: [self-hosted, ARM64]
  core-aarch64-sign:
    needs: core-aarch64-build
    uses: tau-OS/github-actions/.github/workflows/sign-ostree.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      ostreeRef: tau/core/1.1/aarch64
      osName: core-aarch64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  core-aarch64-upload:
    needs: core-aarch64-sign
    uses: tau-OS/github-actions/.github/workflows/upload-ostree.yml@main
    with:
      osName: core-aarch64
    secrets:
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}
  home-aarch64-build:
    uses: tau-OS/github-actions/.github/workflows/build-ostree.yml@main
    with:
      ostreeRef: tau/home/1.1/aarch64
      osVariant: Home
      osName: home-aarch64
      runs-on: [self-hosted, ARM64]
  home-aarch64-sign:
    needs: home-aarch64-build
    uses: tau-OS/github-actions/.github/workflows/sign-ostree.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      ostreeRef: tau/home/1.1/aarch64
      osName: home-aarch64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  home-aarch64-upload:
    needs: home-aarch64-sign
    uses: tau-OS/github-actions/.github/workflows/upload-ostree.yml@main
    with:
      osName: home-aarch64
    secrets:
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}
  workstation-aarch64-build:
    uses: tau-OS/github-actions/.github/workflows/build-ostree.yml@main
    with:
      ostreeRef: tau/workstation/22/aarch64
      osVariant: Workstation
      osName: workstation-aarch64
      unifiedCore: true
      runs-on: [self-hosted, ARM64]
  workstation-aarch64-sign:
    needs: workstation-aarch64-build
    uses: tau-OS/github-actions/.github/workflows/sign-ostree.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      ostreeRef: tau/workstation/22/aarch64
      osName: workstation-aarch64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  workstation-aarch64-upload:
    needs: workstation-aarch64-sign
    uses: tau-OS/github-actions/.github/workflows/upload-ostree.yml@main
    with:
      osName: workstation-aarch64
    secrets:
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}
  server-aarch64-build:
    uses: tau-OS/github-actions/.github/workflows/build-ostree.yml@main
    with:
      ostreeRef: tau/workstation/22/aarch64
      osVariant: Server
      osName: server-aarch64
      unifiedCore: true
      runs-on: [self-hosted, ARM64]
  server-aarch64-sign:
    needs: server-aarch64-build
    uses: tau-OS/github-actions/.github/workflows/sign-ostree.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      ostreeRef: tau/server/22/aarch64
      osName: workstation-aarch64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  server-aarch64-upload:
    needs: server-aarch64-sign
    uses: tau-OS/github-actions/.github/workflows/upload-ostree.yml@main
    with:
      osName: server-aarch64
    secrets:
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}
